include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude:
    # - packages/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    - prefer_single_quotes
    - prefer_relative_imports
    - library_prefixes
    #- unawaited_futures
    #- prefer_final_locals
    #- omit_local_variable_types
